In [1]:
# 객체형

x <-  TRUE #  alt + -
y <-  FALSE # alt + enter

class(x); class(y) # %>% 파이프 연산자 ctrl + shift + m

[1] "logical"

[1] "logical"

In [5]:
# 행렬

x <- matrix(1:20, 5,4) # 1~20의 숫자 값으로 5행 4열 행렬을 생성
x
class(x) # 데이터 구조는 행렬(배열 계열, R 4.0 이하는 matrix만 출력됨)
x[1,2]   # 첫 번째 행, 두 번째 열 위치 선택
x[2:4,]  # 2~4행을 선택, 모든 열을 선택
x[2:4,2] # 2~4행을 선택, 두 번째 열을 선택
x[-2,]   # 2행만 빼고 모두 선택, 모든 열을 선택 / 2~4행을 선택했지만 [1, ] [2, ] [3, ]으로 표현됩니다.

[,1] [,2] [,3] [,4]
[1,] 1     6   11   16  
[2,] 2     7   12   17  
[3,] 3     8   13   18  
[4,] 4     9   14   19  
[5,] 5    10   15   20

[1] "matrix"

[1] 6

[,1] [,2] [,3] [,4]
[1,] 2    7    12   17  
[2,] 3    8    13   18  
[3,] 4    9    14   19

[1] 7 8 9

[,1] [,2] [,3] [,4]
[1,] 1     6   11   16  
[2,] 3     8   13   18  
[3,] 4     9   14   19  
[4,] 5    10   15   20

In [6]:
matrix(1:20,5,4,byrow=TRUE) #행을 기준으로 왼쪽에서 오른쪽으로 채워진 것

[,1] [,2] [,3] [,4]
[1,]  1    2    3    4  
[2,]  5    6    7    8  
[3,]  9   10   11   12  
[4,] 13   14   15   16  
[5,] 17   18   19   20

In [8]:
# 배열: 차원(dim=dimension) 
# 속성을 가진 데이터 구조 array(데이터, c(행개수, 열개수, 차원))

x <- array(1:2,c(5,4,2)) # 1과 2 값으로 5행, 4열, 2차원
x
class(x)

, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    2    1    2
[2,]    2    1    2    1
[3,]    1    2    1    2
[4,]    2    1    2    1
[5,]    1    2    1    2

, , 2

     [,1] [,2] [,3] [,4]
[1,]    1    2    1    2
[2,]    2    1    2    1
[3,]    1    2    1    2
[4,]    2    1    2    1
[5,]    1    2    1    2

[1] "array"

In [10]:
# 리스트 : 숫자나 문자처럼 여러 종류의 자료형을 가질 수 있으며 벡터뿐만 아니라 행렬, 배열 등 데이터 구조도 담을
# 인덱스: 데이터 값이 담긴 색인, 요리 재료 상자의 이름표라고 할 수 있습니다.
# 데이터 위치: 담겨 있는 데이터들의 순서에 따른 위치입니다. 예를 들어 6은 여섯 번째 위치입니다. 데이터 값이 1, 2, 3, 4, 5, 5, 6, 7, …처럼 담겨 있다면 여섯 번째 위치에는 5로 표현됩니다. 데이터 값의 순서에 따른 위치를 표현할 뿐 인덱스나 데이터 값이 아님에 유의하세요. 요리 재료들이 놓인 순서입니다.
# 데이터 값: 인덱스에 담긴 데이터 값입니다. 요리 재료라고 할 수 있습니다.

x <- list(c(1:5),c(1:50)) # 인덱스 1은 1부터 5까지 데이터 값을 가집니다. 인덱스 2는 1부터 50까지 데이터 값을 가집니다.
x

# flower, color는 키, rose, red, white는 밸류
x <- list(flower="rose", color="red","white")  # flower 키는 밸류로 "rose",  color 키는 밸류로 "red", "white"
x # 키(key): 인덱스와 같습니다, 밸류(value): 데이터 값과 같습니다.

[[1]]
[1] 1 2 3 4 5

[[2]]
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
[26] 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50

$flower
[1] "rose"

$color
[1] "red"

[[3]]
[1] "white"

In [15]:
# 데이터 프레임 : 엑셀(Excel)의 데이터 시트를 생각 !!제일 중요!!
# data.frame(열이름 = c(데이터1, 데이터2, ...), 열이름 = c(데이터1, 데이터2, ...), ...)

# 행과 열을 각각 네 개씩 갖는 데이터 프레임
df <- data.frame(name = c("kim", "lee", "choi", "park"), 
                 age = c(32, 25, 18, 39),                
                 height = c(170, 175, 168, 180),         
                 weight = c(63, 66, 59, 70))             
df
class(df)

name age height weight
1 kim  32  170    63    
2 lee  25  175    66    
3 choi 18  168    59    
4 park 39  180    70

[1] "data.frame"

In [17]:
name <- c("kim", "lee", "choi", "park")   # name 변수에 데이터 값을 할당

In [18]:
age <- c(32, 25, 18, 39)    # age 변수에 데이터 값을 할당

In [19]:
height <- c(170, 175, 168, 180)     # weight 변수에 데이터 값을 할당

In [20]:
weight <- c(63, 66, 59, 70)    # height 변수에 데이터 값을 할당

In [21]:
df<-data.frame(name,age,height,weight) # 각 변수를 묶어서 df 변수에 할당,

df   # 각 변수는 열 이름이 됨,열이 지정되지 않았다면 전체를 선택한다는 의미입니다.

name age height weight
1 kim  32  170    63    
2 lee  25  175    66    
3 choi 18  168    59    
4 park 39  180    70

In [24]:
df[1,]  # 첫 번째 행을 선택

df[3,]  # 세 번째 행을 선택

df[c(1,3),]  # 첫 번째와 세 번째 행을 선택


name age height weight
1 kim  32  170    63

name age height weight
3 choi 18  168    59

name age height weight
1 kim  32  170    63    
3 choi 18  168    59

In [26]:
df[1:3,]  # 1~3행을 선택

df[,2] # 두 번째 열을 선택

df[,2, drop = FALSE] # 두 번째 열을 선택, 세로를 출력

name age height weight
1 kim  32  170    63    
2 lee  25  175    66    
3 choi 18  168    59

[1] 32 25 18 39

age
1 32 
2 25 
3 18 
4 39

In [27]:
df[c(1,3),c(1,2)]  # 첫 번째와 세 번째 행, 첫 번째와 두 번째 열을 선택

df[2,2] # 두 번째 행과 두 번째 열에 있는 데이터

name age
1 kim  32 
3 choi 18

[1] 25

In [35]:
rownames(df) <- c('one', 'two', 'three',' four')   # rownames: 행 이름을 붙이는 함수
df

name age height weight
one   kim  32  170    63    
two   lee  25  175    66    
three choi 18  168    59    
 four park 39  180    70

In [40]:
df[c('one', 'three'), ] # 1행과 3열 선택(행)

df[,'age', drop = FALSE] # 나이만 선택(열)

df[c('one', 'three'), c('name', 'age')] # 1행과3행의 이름, 나이를 선택

df$height # ‘데이터프레임$열이름’

name age height weight
one   kim  32  170    63    
three choi 18  168    59

age
one   32 
two   25 
three 18 
 four 39

name age
one   kim  32 
three choi 18

[1] 170 175 168 180

In [98]:
# !! Quiz 1.!!  데이터 프레임 만들기
name <- c('민준', '유리', '재희')
age <- c(22, 20, 21)
gender <- c('남', '여', '남')
major <- c('수학', '영문', '경영')

df <- data.frame(name, age, gender, major)
df

name age gender major
1 민준 22  남     수학 
2 유리 20  여     영문 
3 재희 21  남     경영

In [99]:
# !! Quiz 2.!!  열 별로 전부 각각 데이터 추출하기($ 사용)
df$name
df$age
df$gender
df$major

[1] 민준 유리 재희
Levels: 민준 유리 재희

[1] 22 20 21

[1] 남 여 남
Levels: 남 여

[1] 수학 영문 경영
Levels: 경영 수학 영문

In [100]:
# !! Quiz 3. !! 행 별로 전부 각각 데이터 추출하기

df[1,]

df[2,]

df[3,]

name age gender major
1 민준 22  남     수학

name age gender major
2 유리 20  여     영문

name age gender major
3 재희 21  남     경영

In [101]:
# !! Quiz 4. !! 유리와 재희의 정보만 추출하기
df[c(2,3),]

name age gender major
2 유리 20  여     영문 
3 재희 21  남     경영

In [102]:
# !! Quiz 5. !! 나이와 성별의 정보만 추출하기 ($ 사용)
df$age

df$gender

[1] 22 20 21

[1] 남 여 남
Levels: 남 여

In [103]:
# !! Quiz 6. !! 나이의 평균
age <- c(22, 20, 21)
mean(age)

[1] 21

In [113]:
# !! Quiz 6. !! 성별의 인원수
gender <- c('남', '여', '남')
sum(df$gender)

ERROR: Error in Summary.factor(structure(c(1L, 2L, 1L), .Label = c("남", "여": 'sum' not meaningful for factors
